# Generated by Django 5.1 on 2024-09-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_follow', '0005_livesession_reaction_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='pending', max_length=32)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('artist', 'Artist'), ('subscriber', 'Subscriber')], default='subscriber', max_length=32)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
