# Generated by Django 5.1 on 2024-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_follow', '0009_remove_profile_date_remove_profile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('artist', 'Artist'), ('subscriber', 'Subscriber')], max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE')], max_length=32),
        ),
    ]
