# Generated by Django 5.1 on 2024-09-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_follow', '0010_alter_customuser_role_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('artist', 'Artist'), ('subscriber', 'Subscriber')], default='subscriber', max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='pending', max_length=32),
        ),
    ]
