# Generated by Django 5.1 on 2024-09-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_follow', '0012_alter_customuser_role_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
